#spring:
#  application:
#    name: "employee-management-service"
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  database:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/my_db?useSSL=false
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#
#server:
#  port: 8080
#
#application:
#  endpoint:
#    root: /api/v1
#    employee: /employee
#    task: /task

